package consts

const (
	ID           = "_id"
	CatId        = "catId"
	CommunityId  = "communityId"
	Title        = "title"
	Text         = "text"
	Description  = "description"
	Tags         = "tags"
	UserId       = "userId"
	Flags        = "flags"
	Area         = "area"
	Color        = "color"
	Details      = "details"
	Name         = "name"
	Score        = "_score"
	UpdateAt     = "updateAt"
	CreateAt     = "createAt"
	StartTime    = "startTime"
	EndTime      = "endTime"
	InitiatorIds = "initiatorIds"
	PlanId       = "planId"
	FishNum      = "fishNum"
)
