// Code generated by goctl. DO NOT EDIT.
package mapper

import (
	"context"
	"github.com/xh-polaris/meowchat-collection/biz/infrastructure/data/db"
	"time"

	"github.com/zeromicro/go-zero/core/stores/monc"
	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/bson/primitive"
)

var prefixImageCacheKey = "cache:image:"

type imageModel interface {
	Insert(ctx context.Context, data *db.Image) error
	FindOne(ctx context.Context, id string) (*db.Image, error)
	Update(ctx context.Context, data *db.Image) error
	Delete(ctx context.Context, id string) error
}

type defaultImageModel struct {
	conn *monc.Model
}

func newDefaultImageModel(conn *monc.Model) *defaultImageModel {
	return &defaultImageModel{conn: conn}
}

func (m *defaultImageModel) Insert(ctx context.Context, data *db.Image) error {
	if data.ID.IsZero() {
		data.ID = primitive.NewObjectID()
		data.CreateAt = time.Now()
		data.UpdateAt = time.Now()
	}

	key := prefixImageCacheKey + data.ID.Hex()
	_, err := m.conn.InsertOne(ctx, key, data)
	return err
}

func (m *defaultImageModel) FindOne(ctx context.Context, id string) (*db.Image, error) {
	oid, err := primitive.ObjectIDFromHex(id)
	if err != nil {
		return nil, ErrInvalidObjectId
	}

	var data db.Image
	key := prefixImageCacheKey + id
	err = m.conn.FindOne(ctx, key, &data, bson.M{"_id": oid})
	switch err {
	case nil:
		return &data, nil
	case monc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultImageModel) Update(ctx context.Context, data *db.Image) error {
	data.UpdateAt = time.Now()
	key := prefixImageCacheKey + data.ID.Hex()
	_, err := m.conn.ReplaceOne(ctx, key, bson.M{"_id": data.ID}, data)
	return err
}

func (m *defaultImageModel) Delete(ctx context.Context, id string) error {
	oid, err := primitive.ObjectIDFromHex(id)
	if err != nil {
		return ErrInvalidObjectId
	}
	key := prefixImageCacheKey + id
	_, err = m.conn.DeleteOne(ctx, key, bson.M{"_id": oid})
	return err
}
