// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package provider

import (
	"github.com/xh-polaris/meowchat-collection/biz/adaptor"
	"github.com/xh-polaris/meowchat-collection/biz/application/service"
	"github.com/xh-polaris/meowchat-collection/biz/infrastructure/config"
	"github.com/xh-polaris/meowchat-collection/biz/infrastructure/mapper"
)

// Injectors from wire.go:

func NewCollectionServerImpl() (*adaptor.CollectionServerImpl, error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, err
	}
	catModel := mapper.NewCatModel(configConfig)
	catServiceImpl := &service.CatServiceImpl{
		CatModel: catModel,
	}
	imageModel := mapper.NewImageModel(configConfig)
	imageServiceImpl := &service.ImageServiceImpl{
		ImageModel: imageModel,
	}
	collectionServerImpl := &adaptor.CollectionServerImpl{
		CatService:   catServiceImpl,
		ImageService: imageServiceImpl,
	}
	return collectionServerImpl, nil
}
